var escena=new THREE.Scene();
var camara=new THREE.PerspectiveCamera();
camara.position.z=7;
var renderizador=new THREE.WebGLRenderer();
renderizador.setSize(window.innerHeight*.95,window.innerHeight*.95);
document.body.appendChild(renderizador.domElement);
var forma=new THREE.CylinderGeometry(0.5, 0.5, 2);
var forma2=new THREE.SphereGeometry(1.5,8,6);
var material=new THREE.MeshNormalMaterial();
var cilindro=new THREE.Mesh(forma,material);
var esfera=new THREE.Mesh(forma2,material);
esfera.position.set(0,1.9,0);
escena.add(cilindro,esfera);
renderizador.render(escena,camara);
